{
 "title": "Factorio Tops",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Top Builders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "factorio_top_builders", "legendFormat": "{{nickname}}" }
   ]
  },
  {
   "title": "Top Runners",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "factorio_top_runners", "legendFormat": "{{nickname}}" }
   ]
  },
  {
   "title": "Top Crafters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "factorio_top_crafters", "legendFormat": "{{nickname}}" }
   ]
  },
  {
   "title": "Top Tree Haters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "factorio_top_tree_haters", "legendFormat": "{{nickname}}" }
   ]
  }
 ]
}